### ISSUE TITLE
Fix clang-tidy error introduced in PR #875

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#878]
See https://github.com/solvcon/modmesh/actions/runs/27211548271/job/80341703902 and https://github.com/solvcon/modmesh/actions/runs/27211548271/job/80341703885 :

```
  /home/runner/work/modmesh/modmesh/cpp/modmesh/buffer/SimpleArray.hpp:2097:9: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
   2097 |         ssize_t const dim_length = static_cast<ssize_t>(shape(0));
        |         ^~~~~~~
        |         auto
  /home/runner/work/modmesh/modmesh/cpp/modmesh/buffer/SimpleArray.hpp:2098:9: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
   2098 |         ssize_t const ghost_offset = static_cast<ssize_t>(m_nghost);
        |         ^~~~~~~
        |         auto
  /home/runner/work/modmesh/modmesh/cpp/modmesh/buffer/SimpleArray.hpp:2163:13: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
   2163 |             ssize_t const dim_length = static_cast<ssize_t>(m_shape[dim]);
        |             ^~~~~~~
        |             auto
  14733 warnings generated.
```

This is a real defect slipping through PR CI runs.  @ThreeMonth03 please help fix them.

Related to issue #856.

**Comment by yungyuc** [comment]
@chestercheng @ExplorerRay Could you please also help take a look why PR CI did not capture this clang-tidy error before merging?

**Comment by chestercheng** [comment]
`pilot_clang_tidy_diff` currently checks only `MODMESH_PILOT_FILES`, while `pilot` also links against `modmesh_primary`. 
As a result, the files like `cpp/modmesh/buffer/SimpleArray.hpp` are not detected.

I'll fix this later.

**Comment by yungyuc** [comment]
Resolved by PR #880.
