### PR TITLE
Fix lint error for pr #883

### PR DESCRIPTION
**Pull request by ThreeMonth03**
This pull request fixes lint error in [CI runner](https://github.com/solvcon/solvcon/actions/runs/28519678219/job/84540296079), which is caused by pull request #883.
```
  /Users/runner/work/solvcon/solvcon/cpp/solvcon/python/common.hpp:182:5: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
    182 |     py::ssize_t const itemsize = static_cast<py::ssize_t>(sarr.itemsize());
        |     ^~~~~~~~~~~
        |     auto
  12284 warnings generated.
  Suppressed 12512 warnings (12283 in non-user code, 229 NOLINT).
  Use -header-filter=.* or leave it as default to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
  1 warning treated as error
  make[4]: *** [cpp/solvcon/CMakeFiles/solvcon_primary.dir/buffer/pymod/buffer_pymod.cpp.o] Error 1
  make[4]: *** Waiting for unfinished jobs....
  /Users/runner/work/solvcon/solvcon/cpp/solvcon/python/common.hpp:182:5: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
    182 |     py::ssize_t const itemsize = static_cast<py::ssize_t>(sarr.itemsize());
  
        |     ^~~~~~~~~~~
        |     auto
  12556 warnings generated.
```
Related to #883.

### CODE REVIEW

**Review by yungyuc — APPROVED** [review]
LGTM
