### PR TITLE
Fix SimpleArray clang-tidy use-auto errors

### LINKED ISSUE #856: SimpleArray should handle negative NumPy strides and Python slice semantics consistently
`SimpleArray` does not consistently follow Python/NumPy slicing semantics when negative bounds, negative steps, slice offsets, or negative NumPy strides are involved. Therefore, `SimpleArray` only works reliably when bounds, steps, and strides are positive and the array view starts from the beginning of the underlying buffer.

Affected APIs include:

- [`SimpleArray.__getitem__`](https://github.com/solvcon/modmesh/blob/ee8174b7b559ebef870ab63d0faf91a5c28584a8/cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp#L191-L194), implemented by [`SimpleArray::value_type const & at(ssize_t it)`](https://github.com/solvcon/modmesh/blob/ee8174b7b559ebef870ab63d0faf91a5c28584a8/cpp/modmesh/buffer/SimpleArray.hpp#L1802-L1813)
  - Example: `sarr[-8,-1,-2] = rhs`

- [`SimpleArray.__setitem__`](https://github.com/solvcon/modmesh/blob/master/cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp#L199), implemented by [`ArrayPropertyHelper::setitem_parser()`](https://github.com/solvcon/modmesh/blob/master/cpp/modmesh/buffer/pymod/array_common.hpp#L224-L305)
  - Example: `sarr[-8:-1:2, 8:1:-2] = rhs`

- [`SimpleArray(array=ndarray)` constructor](https://github.com/solvcon/modmesh/blob/master/cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp#L82-L149)
  - Example: `SimpleArrayFloat64(array=ndarr[::-1])`

## Tasks
This issues could be devided to a lot of tasks:
- [x] Support negetive index for [`SimpleArray.__getitem__`](https://github.com/solvcon/modmesh/blob/ee8174b7b559ebef870ab63d0faf91a5c28584a8/cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp#L191-L194). ([PR #875](https://github.com/solvcon/solvcon/pull/875))
- [x] Remove the usage of `SimpleArray::value_type const & at(size_t it)`. ([PR #879](https://github.com/solvcon/solvcon/pull/879))
- [x] Change stride storage from `small_vector<size_t>` to `small_vector<ssize_t>`. ([PR #883](https://github.com/solvcon/solvcon/pull/883))
- [x] Change shape and indices storage from `small_vector<size_t>` to `small_vector<ssize_t>`. ([PR #978](https://github.com/solvcon/solvcon/pull/978))
- [x] Fix [SimpleArray.__setitem__](https://github.com/solvcon/modmesh/blob/master/cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp#L199) by normalizing slice bounds, steps, and lengths with `pybind11::slice::compute()` and honoring the input NumPy strides, destination storage strides, slice starts, and slice steps. ([PR #857](https://github.com/solvcon/solvcon/pull/857))
- [x] Correct the buffer and logical-origin representation for NumPy views. The NumPy-array constructor currently uses the logical origin (`view_ptr`) as the start of `ConcreteBuffer`, so a negative-strided view omits valid elements before that pointer. The original view may still work because the complete NumPy allocation remains alive, but `clone()` copies only the incomplete range declared by `ConcreteBuffer` while retaining the original shape and strides. Reading the clone can then access memory before its allocation. See the [NumPy-array constructor](https://github.com/solvcon/solvcon/blob/master/cpp/solvcon/buffer/pymod/wrap_SimpleArray.hpp#L83-L126) and the [`SimpleArray` copy constructor](https://github.com/solvcon/solvcon/blob/master/cpp/solvcon/buffer/SimpleArray.hpp#L1767-L1773). ([PR #1101](https://github.com/solvcon/solvcon/pull/1101))
- [x] Support negative strides for `as_mdspan`, which includes: ([PR #1102](https://github.com/solvcon/solvcon/pull/1102))
  - [x] Add an internal signed-stride mdspan layout mapping. The current `std::layout_stride` mapping cannot safely represent negative strides and their logical-origin offset. ([PR #1102](https://github.com/solvcon/solvcon/pull/1102))
  - [x] Use the signed-stride mapping in `SimpleArray::as_mdspan()`. ([PR #1102](https://github.com/solvcon/solvcon/pull/1102))
- [x] Verify that the related issues continue to behave correctly. ([PR #875](https://github.com/solvcon/solvcon/pull/875), [PR #879](https://github.com/solvcon/solvcon/pull/879), [PR #883](https://github.com/solvcon/solvcon/pull/883), [PR #1094](https://github.com/solvcon/solvcon/pull/1094))

## Related Issues
* issue #580
* issue #603

## How to reproduce the error
```shell
$ python3 - <<'PY'
import numpy as np
import modmesh

ndarr_shape = (8, 9, 10, 11, 12)
ndarr = np.arange(np.prod(ndarr_shape), dtype='float64')
ndarr = ndarr.reshape(ndarr_shape)
expected = ndarr.copy()
sarr = modmesh.SimpleArrayFloat64(array=ndarr)

key = np.index_exp[-8:-1:2, 8:1:-2, 1:-1:3, ..., -2:-8:-2]
value_shape = expected[key].shape

value = np.empty(value_shape, dtype='float64')
next_value = 1000.0
for i0 in range(value_shape[0]):
    for i1 in range(value_shape[1]):
        for i2 in range(value_shape[2]):
            for i3 in range(value_shape[3]):
                for i4 in range(value_shape[4]):
                    value[i0, i1, i2, i3, i4] = next_value
                    next_value += 1

sarr[key] = value
expected[key] = value
np.testing.assert_array_equal(sarr.ndarray, expected)
PY
Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
RuntimeError: Broadcast input array from shape(4, 4, 3, 11, 3) into shape(4, 4, 1, 11, 3)
```

```shell
$ python3 - <<'PY'
import numpy as np
import modmesh

ndarr_shape = (16, 18, 20, 22, 24)
ndarr = np.arange(np.prod(ndarr_shape), dtype='float64')
ndarr = ndarr.reshape(ndarr_shape)

view = ndarr[15::-2, 1::2, 19::-2, 1::2, 23::-2]
expected = np.array(view, copy=True)
sarr = modmesh.SimpleArrayFloat64(array=view)

key = np.index_exp[::-2, 1:-1:2, -8:-1:2, 10:2:-3, ...]
value_shape = expected[key].shape

value = np.empty(value_shape, dtype='float64')
next_value = 1000.0
for i0 in range(value_shape[0]):
    for i1 in range(value_shape[1]):
        for i2 in range(value_shape[2]):
            for i3 in range(value_shape[3]):
                for i4 in range(value_shape[4]):
                    value[i0, i1, i2, i3, i4] = next_value
                    next_value += 1

sarr[key] = value
expected[key] = value
np.testing.assert_array_equal(view, expected)
PY
Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
RuntimeError: Broadcast input array from shape(4, 4, 4, 3, 12) into shape(18446744073709551612, 18446744073709551615, 4, 3, 12)
```

### How to reproduce the buffer-origin error

This example uses the same negative-strided NumPy view as PR #857.

The original `sarr` may still read correctly because the complete NumPy allocation remains alive, even though `ConcreteBuffer` omits elements before the view origin. `clone()` copies only that incomplete declared range while retaining the negative strides. Reading `clone.ndarray` then accesses memory before the cloned allocation and exits with status 139 (SIGSEGV).

```shell
$ python3 -u - <<'PY'
import numpy as np
import solvcon

ndarr_shape = (16, 18, 20, 22, 24)
ndarr = np.arange(np.prod(ndarr_shape), dtype='float64')
ndarr = ndarr.reshape(ndarr_shape)

view = ndarr[15::-2, 1::2, 19::-2, 1::2, 23::-2]
sarr = solvcon.SimpleArrayFloat64(array=view)

print("view shape:", view.shape)
print(
    "view strides:",
    tuple(stride // view.itemsize for stride in view.strides),
)
print("source sample:", sarr[1, 2, 3, 4, 5])

clone = sarr.clone()
print("clone created")

np.testing.assert_array_equal(clone.ndarray, view)
PY
view shape: (8, 9, 10, 11, 12)
view strides: (-380160, 21120, -1056, 48, -2)
source sample: 2530933.0
clone created
Segmentation fault (core dumped)
```

### LINKED ISSUE #878: Fix clang-tidy error introduced in PR #875
See https://github.com/solvcon/modmesh/actions/runs/27211548271/job/80341703902 and https://github.com/solvcon/modmesh/actions/runs/27211548271/job/80341703885 :

```
  /home/runner/work/modmesh/modmesh/cpp/modmesh/buffer/SimpleArray.hpp:2097:9: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
   2097 |         ssize_t const dim_length = static_cast<ssize_t>(shape(0));
        |         ^~~~~~~
        |         auto
  /home/runner/work/modmesh/modmesh/cpp/modmesh/buffer/SimpleArray.hpp:2098:9: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
   2098 |         ssize_t const ghost_offset = static_cast<ssize_t>(m_nghost);
        |         ^~~~~~~
        |         auto
  /home/runner/work/modmesh/modmesh/cpp/modmesh/buffer/SimpleArray.hpp:2163:13: error: use auto when initializing with a cast to avoid duplicating the type name [modernize-use-auto,-warnings-as-errors]
   2163 |             ssize_t const dim_length = static_cast<ssize_t>(m_shape[dim]);
        |             ^~~~~~~
        |             auto
  14733 warnings generated.
```

This is a real defect slipping through PR CI runs.  @ThreeMonth03 please help fix them.

Related to issue #856.

### PR DESCRIPTION
**Pull request by ThreeMonth03**
Clang-tidy error was found after mergeing #875, so this pull request fixes the corresponding clang-tidy error.

Related to #878.

### CODE REVIEW

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 1]
```diff
@@ -2160,7 +2160,7 @@ class SimpleArray
         shape_type normalized(idx.size());
         for (size_t dim = 0; dim < m_shape.size(); ++dim)
         {
-            ssize_t const dim_length = static_cast<ssize_t>(m_shape[dim]);
+            auto const dim_length = static_cast<ssize_t>(m_shape[dim]);
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp:2163]: Replace explicit type with `auto` to avoid duplicate the type name.

**Review by ThreeMonth03 — COMMENTED** [review]
@yungyuc Please take a look.

**Review by yungyuc — APPROVED** [review]
LGTM

**Review by tigercosmos — COMMENTED** [review]
LGTM, maybe explictly mention this to the style doc for AI.
